import '../model/world_trend.dart';

class WorldService {
  Future<List<WorldTrend>> getTop50WorldTrends() async {
    await Future.delayed(const Duration(milliseconds: 800));
    
    final now = DateTime.now();
    return [
      WorldTrend(rank: 1, title: 'AI Revolution Continues', description: 'ChatGPT-5 announcement breaks internet records', category: 'Technology', source: 'OpenAI', region: 'Global', engagement: 2500000, timestamp: now.subtract(const Duration(minutes: 30)), imageUrl: 'https://picsum.photos/400/300?random=50'),
      WorldTrend(rank: 2, title: 'Climate Summit Agreement', description: 'Historic climate deal reached by 195 countries', category: 'Politics', source: 'UN Climate', region: 'Global', engagement: 2200000, timestamp: now.subtract(const Duration(hours: 1)), countryFlag: '🌍'),
      WorldTrend(rank: 3, title: 'World Cup Final Drama', description: 'Penalty shootout decides championship', category: 'Sports', source: 'FIFA', region: 'Qatar', engagement: 2100000, timestamp: now.subtract(const Duration(hours: 2)), countryFlag: '🇶🇦'),
      WorldTrend(rank: 4, title: 'Bollywood Mega Hit', description: 'New film breaks all box office records globally', category: 'Entertainment', source: 'Bollywood', region: 'India', engagement: 1900000, timestamp: now.subtract(const Duration(hours: 3)), countryFlag: '🇮🇳'),
      WorldTrend(rank: 5, title: 'Space Mission Success', description: 'Mars rover discovers potential signs of life', category: 'Science', source: 'NASA', region: 'USA', engagement: 1800000, timestamp: now.subtract(const Duration(hours: 4)), countryFlag: '🇺🇸'),
      WorldTrend(rank: 6, title: 'K-Pop Global Phenomenon', description: 'BTS announces world tour, tickets sell out instantly', category: 'Entertainment', source: 'BigHit Music', region: 'South Korea', engagement: 1750000, timestamp: now.subtract(const Duration(hours: 5)), countryFlag: '🇰🇷'),
      WorldTrend(rank: 7, title: 'Cryptocurrency Surge', description: 'Bitcoin reaches new all-time high amid institutional adoption', category: 'Finance', source: 'CoinBase', region: 'Global', engagement: 1700000, timestamp: now.subtract(const Duration(hours: 6))),
      WorldTrend(rank: 8, title: 'Royal Wedding Announcement', description: 'British Royal Family announces surprise engagement', category: 'Royal', source: 'Buckingham Palace', region: 'UK', engagement: 1650000, timestamp: now.subtract(const Duration(hours: 7)), countryFlag: '🇬🇧'),
      WorldTrend(rank: 9, title: 'Anime Studio Breakthrough', description: 'Studio Ghibli announces first AI-assisted animation', category: 'Entertainment', source: 'Studio Ghibli', region: 'Japan', engagement: 1600000, timestamp: now.subtract(const Duration(hours: 8)), countryFlag: '🇯🇵'),
      WorldTrend(rank: 10, title: 'Medical Breakthrough', description: 'New cancer treatment shows 95% success rate in trials', category: 'Health', source: 'WHO', region: 'Switzerland', engagement: 1550000, timestamp: now.subtract(const Duration(hours: 9)), countryFlag: '🇨🇭'),
      WorldTrend(rank: 11, title: 'Electric Vehicle Revolution', description: 'Tesla announces 15k model, pre-orders exceed 1M', category: 'Technology', source: 'Tesla', region: 'USA', engagement: 1500000, timestamp: now.subtract(const Duration(hours: 10)), countryFlag: '🇺🇸'),
      WorldTrend(rank: 12, title: 'Olympic Record Broken', description: 'Swimming world record shattered by 2 seconds', category: 'Sports', source: 'Olympics', region: 'France', engagement: 1450000, timestamp: now.subtract(const Duration(hours: 11)), countryFlag: '🇫🇷'),
      WorldTrend(rank: 13, title: 'Social Media Outage', description: 'Global platforms down for 6 hours, billions affected', category: 'Technology', source: 'Meta', region: 'Global', engagement: 1400000, timestamp: now.subtract(const Duration(hours: 12))),
      WorldTrend(rank: 14, title: 'Fashion Week Sensation', description: 'Sustainable fashion takes center stage in Paris', category: 'Fashion', source: 'Paris Fashion Week', region: 'France', engagement: 1350000, timestamp: now.subtract(const Duration(hours: 13)), countryFlag: '🇫🇷'),
      WorldTrend(rank: 15, title: 'Gaming Championship', description: 'Esports tournament breaks viewership records', category: 'Gaming', source: 'Riot Games', region: 'Global', engagement: 1300000, timestamp: now.subtract(const Duration(hours: 14))),
      WorldTrend(rank: 16, title: 'Music Festival Lineup', description: 'Coachella announces star-studded 2025 lineup', category: 'Music', source: 'Coachella', region: 'USA', engagement: 1250000, timestamp: now.subtract(const Duration(hours: 15)), countryFlag: '🇺🇸'),
      WorldTrend(rank: 17, title: 'Political Election Results', description: 'Surprise victory in major European election', category: 'Politics', source: 'EU Parliament', region: 'Germany', engagement: 1200000, timestamp: now.subtract(const Duration(hours: 16)), countryFlag: '🇩🇪'),
      WorldTrend(rank: 18, title: 'Viral Dance Challenge', description: 'New TikTok dance reaches 1 billion views', category: 'Social Media', source: 'TikTok', region: 'Global', engagement: 1150000, timestamp: now.subtract(const Duration(hours: 17))),
      WorldTrend(rank: 19, title: 'Food Trend Explosion', description: 'Korean corn dogs become global street food sensation', category: 'Food', source: 'Food Network', region: 'South Korea', engagement: 1100000, timestamp: now.subtract(const Duration(hours: 18)), countryFlag: '🇰🇷'),
      WorldTrend(rank: 20, title: 'Tech IPO Launch', description: 'AI startup valued at 100B in largest IPO ever', category: 'Business', source: 'NASDAQ', region: 'USA', engagement: 1050000, timestamp: now.subtract(const Duration(hours: 19)), countryFlag: '🇺🇸'),
      WorldTrend(rank: 21, title: 'Environmental Victory', description: 'Amazon rainforest deforestation hits 10-year low', category: 'Environment', source: 'WWF', region: 'Brazil', engagement: 1000000, timestamp: now.subtract(const Duration(hours: 20)), countryFlag: '🇧🇷'),
      WorldTrend(rank: 22, title: 'Celebrity Scandal', description: 'Hollywood A-lister announces surprise retirement', category: 'Celebrity', source: 'Entertainment Tonight', region: 'USA', engagement: 950000, timestamp: now.subtract(const Duration(hours: 21)), countryFlag: '🇺🇸'),
      WorldTrend(rank: 23, title: 'Scientific Discovery', description: 'New species discovered in deep ocean expedition', category: 'Science', source: 'National Geographic', region: 'Global', engagement: 900000, timestamp: now.subtract(const Duration(hours: 22))),
      WorldTrend(rank: 24, title: 'Art Auction Record', description: 'Digital NFT artwork sells for 50 million', category: 'Art', source: 'Sothebys', region: 'UK', engagement: 850000, timestamp: now.subtract(const Duration(hours: 23)), countryFlag: '🇬🇧'),
      WorldTrend(rank: 25, title: 'Travel Boom Returns', description: 'International tourism reaches pre-pandemic levels', category: 'Travel', source: 'UNWTO', region: 'Global', engagement: 800000, timestamp: now.subtract(const Duration(days: 1))),
      WorldTrend(rank: 26, title: 'Startup Unicorn', description: 'EdTech company reaches 1B valuation overnight', category: 'Business', source: 'TechCrunch', region: 'India', engagement: 750000, timestamp: now.subtract(const Duration(days: 1, hours: 1)), countryFlag: '🇮🇳'),
      WorldTrend(rank: 27, title: 'Weather Phenomenon', description: 'Rare aurora visible across entire Northern Hemisphere', category: 'Weather', source: 'NASA', region: 'Global', engagement: 700000, timestamp: now.subtract(const Duration(days: 1, hours: 2))),
      WorldTrend(rank: 28, title: 'Culinary Innovation', description: 'Lab-grown meat approved for commercial sale globally', category: 'Food Tech', source: 'FDA', region: 'Global', engagement: 650000, timestamp: now.subtract(const Duration(days: 1, hours: 3))),
      WorldTrend(rank: 29, title: 'Social Movement', description: 'Global youth climate strike draws millions', category: 'Activism', source: 'Fridays for Future', region: 'Global', engagement: 600000, timestamp: now.subtract(const Duration(days: 1, hours: 4))),
      WorldTrend(rank: 30, title: 'Gaming Release', description: 'Most anticipated game of the year launches globally', category: 'Gaming', source: 'Sony PlayStation', region: 'Japan', engagement: 550000, timestamp: now.subtract(const Duration(days: 1, hours: 5)), countryFlag: '🇯🇵'),
      WorldTrend(rank: 31, title: 'Fashion Collaboration', description: 'Luxury brand partners with sustainable fashion startup', category: 'Fashion', source: 'Vogue', region: 'Italy', engagement: 500000, timestamp: now.subtract(const Duration(days: 1, hours: 6)), countryFlag: '🇮🇹'),
      WorldTrend(rank: 32, title: 'Sports Upset', description: 'Underdog team wins championship in stunning upset', category: 'Sports', source: 'ESPN', region: 'USA', engagement: 450000, timestamp: now.subtract(const Duration(days: 1, hours: 7)), countryFlag: '🇺🇸'),
      WorldTrend(rank: 33, title: 'Tech Merger', description: 'Two tech giants announce 200B merger deal', category: 'Business', source: 'Reuters', region: 'Global', engagement: 400000, timestamp: now.subtract(const Duration(days: 1, hours: 8))),
      WorldTrend(rank: 34, title: 'Cultural Festival', description: 'Diwali celebrations break attendance records worldwide', category: 'Culture', source: 'Cultural Times', region: 'India', engagement: 350000, timestamp: now.subtract(const Duration(days: 1, hours: 9)), countryFlag: '🇮🇳'),
      WorldTrend(rank: 35, title: 'Health Innovation', description: 'Wearable device can predict illness 3 days early', category: 'Health Tech', source: 'Apple Health', region: 'USA', engagement: 300000, timestamp: now.subtract(const Duration(days: 1, hours: 10)), countryFlag: '🇺🇸'),
      WorldTrend(rank: 36, title: 'Music Collaboration', description: 'East meets West in unprecedented music fusion', category: 'Music', source: 'Spotify', region: 'Global', engagement: 280000, timestamp: now.subtract(const Duration(days: 1, hours: 11))),
      WorldTrend(rank: 37, title: 'Educational Reform', description: 'Finland announces revolutionary education system', category: 'Education', source: 'Education Weekly', region: 'Finland', engagement: 260000, timestamp: now.subtract(const Duration(days: 1, hours: 12)), countryFlag: '🇫🇮'),
      WorldTrend(rank: 38, title: 'Renewable Energy', description: 'Solar power becomes cheapest energy source globally', category: 'Energy', source: 'IEA', region: 'Global', engagement: 240000, timestamp: now.subtract(const Duration(days: 1, hours: 13))),
      WorldTrend(rank: 39, title: 'Archaeological Find', description: 'Ancient civilization discovered using satellite imagery', category: 'Archaeology', source: 'National Geographic', region: 'Peru', engagement: 220000, timestamp: now.subtract(const Duration(days: 1, hours: 14)), countryFlag: '🇵🇪'),
      WorldTrend(rank: 40, title: 'Automotive Innovation', description: 'Self-driving cars approved for public roads', category: 'Transportation', source: 'Waymo', region: 'USA', engagement: 200000, timestamp: now.subtract(const Duration(days: 1, hours: 15)), countryFlag: '🇺🇸'),
      WorldTrend(rank: 41, title: 'Streaming Wars', description: 'New platform launches with exclusive content', category: 'Entertainment', source: 'Variety', region: 'Global', engagement: 180000, timestamp: now.subtract(const Duration(days: 1, hours: 16))),
      WorldTrend(rank: 42, title: 'Fitness Revolution', description: 'VR fitness becomes mainstream workout method', category: 'Fitness', source: 'Fitness Magazine', region: 'Global', engagement: 160000, timestamp: now.subtract(const Duration(days: 1, hours: 17))),
      WorldTrend(rank: 43, title: 'Cryptocurrency News', description: 'Central banks announce digital currency trials', category: 'Finance', source: 'Financial Times', region: 'Global', engagement: 140000, timestamp: now.subtract(const Duration(days: 1, hours: 18))),
      WorldTrend(rank: 44, title: 'Space Tourism', description: 'Commercial space flights become affordable', category: 'Space', source: 'SpaceX', region: 'USA', engagement: 120000, timestamp: now.subtract(const Duration(days: 1, hours: 19)), countryFlag: '🇺🇸'),
      WorldTrend(rank: 45, title: 'Mental Health', description: 'Global initiative launches for mental wellness', category: 'Health', source: 'WHO', region: 'Global', engagement: 100000, timestamp: now.subtract(const Duration(days: 1, hours: 20))),
      WorldTrend(rank: 46, title: 'Robotics Advance', description: 'Humanoid robots enter consumer market', category: 'Robotics', source: 'Boston Dynamics', region: 'USA', engagement: 90000, timestamp: now.subtract(const Duration(days: 1, hours: 21)), countryFlag: '🇺🇸'),
      WorldTrend(rank: 47, title: 'Agricultural Tech', description: 'Vertical farming solves food security crisis', category: 'Agriculture', source: 'AgTech News', region: 'Netherlands', engagement: 80000, timestamp: now.subtract(const Duration(days: 1, hours: 22)), countryFlag: '🇳🇱'),
      WorldTrend(rank: 48, title: 'Ocean Conservation', description: 'Largest marine protected area established', category: 'Conservation', source: 'Ocean Conservancy', region: 'Global', engagement: 70000, timestamp: now.subtract(const Duration(days: 1, hours: 23))),
      WorldTrend(rank: 49, title: 'Quantum Computing', description: 'Quantum computer solves impossible problem', category: 'Computing', source: 'IBM', region: 'USA', engagement: 60000, timestamp: now.subtract(const Duration(days: 2)), countryFlag: '🇺🇸'),
      WorldTrend(rank: 50, title: 'Cultural Exchange', description: 'Global art exhibition connects 100 museums', category: 'Art', source: 'UNESCO', region: 'Global', engagement: 50000, timestamp: now.subtract(const Duration(days: 2, hours: 1))),
    ];
  }
}
   